version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-net
    container_name: app
    env_file:
      - ./.env
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-net
    container_name: db
    env_file:
      - ./.env

volumes:
  app-db:

networks:
  app-net:
    driver: bridge